# Preface {.unnumbered}

Pharmacometrics is an interdisciplinary science requiring domain knowledge and technical expertise from a range of disciplines including pharmacology, statistics, and data science. Developing proficiency in each of these domains is a daunting task for students as most will come from a basic science, clinical, or statistics background and attempt to fill in their knowledge gaps along the way. When I was in pharmacy school and during my fellowship training, I found the best way for me to learn was to code up models myself and explore them through simulation. If you can simulate a data-generating process, you really understand it and will be able to accurately interpret the parameter estimates obtained from model fitting. My goal in writing/developing "A Student's Guide to Pharmacometrics" is to create the learning-resource I always wished I had. I want to provide you with a resource hub to learn about a vast array of models and topics in pharmacometrics to build your competence as quickly as possible so that you can help grow the field through your own contributions. I assume you are comfortable with basic and clinical pharmacology concepts and have some familiarity with R. I take a very technical approach to demonstrating concepts and models by providing model code and simulations for each model. I encourage you to copy and paste the code from this document and explore these models yourself by changing their parameter values and building on their complexity. I sincerely hope you find this resource useful. -TD
